image: Ubuntu  # образ для сборки

stack: jdk 1.8  # версия JDK

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-mbank.jar &
  - chmod +x gradlew
build_script:
  - ./gradlew test --info